services:
  server:
    restart: "unless-stopped"
    ports:
      - 5001:5001/udp
      - 5002:5002/tcp
      - 5000:5000/tcp
    environment:
      - EULA=true
      - ENABLE_QUERY=true
      - ENABLE_RCON=true
      - QUERY_PORT=5001
      - RCON_PORT=5002
      - RCON_PASSWORD=123456
      - GUI=false
      - SERVER_PORT=5000
    image: itzg/minecraft-server